
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[372] =
    {   0,
        0,    0,  101,  100,   98,   96,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,    0,   98,   95,
        0,    0,    0,   89,   22,    0,    0,    0,    0,    0,
        0,    3,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   39,    0,    0,
        0,    0,    0,    0,   92,   34,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   64,    0,    0,    0,   99,   98,   94,    0,
       14,    0,   16,   19,   53,    0,    0,    0,    0,    0,

        0,    0,    6,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   43,
        0,    0,    0,    0,    0,    0,   40,   17,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   83,    0,
        0,    0,    0,    0,   84,    0,    0,    0,    0,    0,
        0,   23,    0,    0,    0,   20,   85,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   37,
       91,    0,    0,    0,    4,    0,    0,   42,    0,    0,
       48,    0,   31,    0,   11,    0,   38,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   55,

        0,   32,    0,   36,    0,   27,    8,    0,   78,    0,
        5,    0,    0,    0,    0,   86,   51,    0,    0,    0,
       65,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       75,    0,    0,    7,    0,    0,    0,    0,    0,    0,
        0,    0,   35,    0,    0,   49,    0,    0,   33,    0,
        0,    0,   61,    0,   76,    0,   54,   68,    0,    0,
        9,    0,   79,   93,    0,   62,   15,   67,   41,    0,
        0,   80,    0,    0,    0,   47,    0,   10,    0,    0,
        0,    0,    0,    0,    2,   90,    0,   56,    0,    0,
        0,    0,   24,    0,    0,   18,    0,   88,    0,    0,

       52,   77,    0,   25,    0,   29,   60,    0,    0,    0,
        0,    0,    0,   26,    0,    0,    0,   59,   69,    0,
       57,    0,    0,    0,   12,   58,    0,   46,    0,   50,
        0,   71,    0,    0,   82,    0,    0,    0,   70,    0,
       45,    0,   72,   66,    1,    0,   30,    0,    0,    0,
       74,    0,    0,   13,    0,   81,    0,    0,    0,   73,
        0,    0,    0,    0,   21,   44,    0,    0,   63,   87,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    5,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    6,    7,    8,    9,

       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[32] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst flex_uint16_t yy_base[373] =
    {   0,
        0,    0,  379,  380,  375,   28,   17,   29,   34,   35,
       31,   32,   36,   32,   32,  357,  380,   51,   57,  356,
       57,   64,  349,   58,   82,   58,  364,  370,  369,   85,
      351,   82,   61,  380,  380,  346,  344,  344,  348,  346,
      342,  380,  345,  338,  350,   87,  355,  352,  333,  335,
      337,  329,  345,  337,  332,  327,  331,  326,  335,  329,
      328,   50,  340,  320,  380,  334,  329,  329,  316,   76,
      317,  325,  328,  331,   76,  324,  317,  322,  324,  306,
      313,   95,  380,  316,   83,  306,  325,  324,  380,  307,
      380,  308,  380,  300,  380,  313,  294,  311,  295,  296,

      310,  293,  291,  292,  296,  302,  287,  297,  282,  296,
       96,  284,  289,  296,  299,  293,  283,   97,  278,  380,
      282,  288,  289,  284,  281,  272,  380,  380,  283,  284,
      269,  107,  268,  270,  271,  262,  279,  273,  262,  272,
      274,  265,  272,  275,  380,   96,  102,  256,  259,  272,
      269,  380,  251,  263,  264,  380,  380,  263,  264,  261,
      261,  252,  243,  253,  256,  255,  254,  257,  253,  380,
      241,  243,  242,  233,  380,  238,  231,  380,  230,  231,
      380,  245,  380,  227,  380,  232,  380,  224,  235,  225,
      233,  229,  221,  230,  233,  217,  227,  217,  213,  380,

      213,  380,  227,  212,  212,  380,  380,  211,  380,  223,
      380,  206,  212,  220,  219,  380,  110,  218,  202,  203,
      201,  214,  200,  203,  211,  195,  196,  199,  207,  191,
      191,  208,  208,  380,  202,  201,  186,  199,  195,  195,
      183,  186,  380,  195,  186,  380,  183,  182,  176,  179,
      184,  173,  380,  177,  380,  185,  380,  380,  182,  181,
      380,  163,  380,  380,  172,  170,  165,  380,  380,  162,
      175,  162,  175,  174,  175,  380,  169,  380,  156,  170,
      156,  159,  167,  159,  380,  380,  165,  380,  164,  163,
      160,  162,  380,  144,  152,  380,  143,  380,  154,  149,

      380,  380,  142,  380,  156,  380,  380,  140,  143,  151,
      150,  149,  146,  380,  131,  148,  145,  380,  380,  137,
      380,  139,  128,  145,  380,  380,  140,  125,  123,  380,
      139,  380,  123,  122,  380,  120,  118,  118,  380,  133,
      380,  115,  380,  380,  380,  129,  380,  132,  127,  122,
      380,  109,  123,  380,  114,  380,  103,  113,  106,  380,
      116,  108,  119,  118,  380,  380,   72,   60,  380,  380,
      380,   74
    } ;

static yyconst flex_int16_t yy_def[373] =
    {   0,
      371,    1,  371,  371,  372,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  372,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  372,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
        0,  371
    } ;

static yyconst flex_uint16_t yy_nxt[412] =
    {   0,
        4,    4,    5,    6,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   17,   27,   17,   17,   17,
       17,   30,   30,   31,   36,   32,   48,   54,   37,   33,
       34,   35,   38,   39,   45,   50,   40,   41,   46,   52,
       56,   42,   49,   43,   51,   57,   58,   47,   53,   44,
       60,   55,   62,   75,   61,  124,   63,   65,   94,   70,
       82,   76,  125,   71,   28,   66,  370,   83,   95,   67,
       84,   68,   69,   72,  138,   85,   73,   77,   89,   89,
       91,   78,  105,   92,  369,   79,  151,  106,  132,  133,

      146,  172,  152,   80,  147,  139,  180,   81,  148,  173,
      107,   93,  192,  108,  206,  208,  181,  149,  263,  209,
      207,  361,  362,  368,  367,  210,  366,  365,  364,  363,
      360,  193,  359,  264,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,

      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  191,  190,  189,  188,  187,  186,  185,  184,

      183,  182,  179,  178,  177,  176,  175,  174,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,   88,   87,  153,  150,
      145,  144,  143,  142,  141,  140,  137,  136,  135,  134,
      131,  130,  129,  128,  127,  126,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  114,  113,  112,  111,  110,
      109,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       90,   88,   87,   86,   74,   64,   59,   29,  371,    3,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371
    } ;

static yyconst flex_int16_t yy_chk[412] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    6,    7,    8,    7,   11,   14,    8,    7,
        7,    7,    8,    9,   10,   12,    9,    9,   10,   13,
       15,    9,   11,    9,   12,   15,   15,   10,   13,    9,
       18,   14,   19,   24,   18,   62,   19,   21,   33,   22,
       26,   24,   62,   22,  372,   21,  368,   26,   33,   21,
       26,   21,   21,   22,   75,   26,   22,   25,   30,   30,
       32,   25,   46,   32,  367,   25,   85,   46,   70,   70,

       82,  111,   85,   25,   82,   75,  118,   25,   82,  111,
       46,   32,  132,   46,  146,  147,  118,   82,  217,  147,
      146,  357,  357,  364,  363,  147,  362,  361,  359,  358,
      355,  132,  353,  217,  352,  350,  349,  348,  346,  342,
      340,  338,  337,  336,  334,  333,  331,  329,  328,  327,
      324,  323,  322,  320,  317,  316,  315,  313,  312,  311,
      310,  309,  308,  305,  303,  300,  299,  297,  295,  294,
      292,  291,  290,  289,  287,  284,  283,  282,  281,  280,
      279,  277,  275,  274,  273,  272,  271,  270,  267,  266,
      265,  262,  260,  259,  256,  254,  252,  251,  250,  249,

      248,  247,  245,  244,  242,  241,  240,  239,  238,  237,
      236,  235,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  215,  214,
      213,  212,  210,  208,  205,  204,  203,  201,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      186,  184,  182,  180,  179,  177,  176,  174,  173,  172,
      171,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  155,  154,  153,  151,  150,  149,  148,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  131,  130,  129,  126,  125,  124,  123,  122,

      121,  119,  117,  116,  115,  114,  113,  112,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   96,   94,   92,   90,   88,   87,   86,   84,
       81,   80,   79,   78,   77,   76,   74,   73,   72,   71,
       69,   68,   67,   66,   64,   63,   61,   60,   59,   58,
       57,   56,   55,   54,   53,   52,   51,   50,   49,   48,
       47,   45,   44,   43,   41,   40,   39,   38,   37,   36,
       31,   29,   28,   27,   23,   20,   16,    5,    3,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokenize.l"
#line 2 "tokenize.l"
#include<stdio.h>
#include<string.h>
#include<math.h>
#include<stdlib.h>
#include "./y.tab.h"
#define true 1
#define false 0
#define bool int

//prints all lexical phase information
#define TDEBUG 1

char *strdump(char* str) {
  char *ret = (char*)malloc(sizeof(char)*1000);
  int i=0;
  while(str[i]!='\0') {
    ret[i] = str[i];
    i++;
  }
  ret[i] = '\0';
  return ret;
}

double toDouble(char str[]) {
  int length = 0;
  int i = 0;
  while(str[i] != '\0') {
    i++;
    length++;
  }
  bool decimal = false;
  double n = 0;
  double power = 1;
  if(str[0] == '-')
    i=1;
  else
    i=0;
  for(;i<length;i++) {
    if(str[i] == '.') {
      decimal = true;
      power = 10;
      continue;
    }
    if(decimal) {
      n = n + (str[i] - '0')/power;
      power = power*10;
    } else {
      n = n*10 + (str[i] - '0');
    }
  }
  if(str[0] == '-')
    n*=(-1);
  return n;
}

#line 734 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 62 "tokenize.l"

#line 954 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 372 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 380 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CONSTRUCT_T;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return LENGTH_T;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CM_T;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return FROM_T;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return THIS_T;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CUT_T;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return GIVEN_T;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return THAT_T;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return TWICE_T;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return EQUALS_T;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return LINE_T;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return SEGMENT_T;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return DIFFERENCE_T;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return AND_T;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CENTER_T;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ANY_T;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ANY_T;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return RADIUS_T;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ARC_T;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ARCS_T;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return INTERSECTING_T;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return AT_T;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return TWO_T;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return POINTS_T;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CENTERS_T;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return GREATER_T;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return THAN_T;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ARCS_T;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CUTTING_T;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return EACHOTHER_T;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return JOIN_T;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return SAME_T;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return POINT_T;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ON_T;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return OTHER_T;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return SIDE_T;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return DRAW_T;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return MARK_T;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return IT_T;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return NOT_T;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CIRCLE_T;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return HALF_T;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ITS_T;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return INTERSECTION_T;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return PREVIOUS_T;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return BISECTOR_T;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return DIVIDE_T;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return INTO_T;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return PARTS_T;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return DIAMETER_T;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ANGLE_T;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return VERTEX_T;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ARM_T;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return THEIR_T;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return RAYS_T;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ORIGIN_T;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return PASSING_T;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return THROUGH_T;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return MEASURE_T;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return DEGREES_T;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return RIGHT_T;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 124 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return BISECT_T;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 125 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return PERPENDICULAR_T;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 126 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return TO_T;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 127 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CHORD_T;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 128 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return BISECTORS_T;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 129 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return CHORDS_T;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 130 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return THESE_T;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 131 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return OUTSIDE_T;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 132 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return PARALLEL_T;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 133 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return DISTANCE_T;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 134 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return TRIANGLE_T;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 135 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return EQUILATERAL_T;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 136 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ISOSCELES_T;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 137 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return EQUAL_T;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 138 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return SIDES_T;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 139 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return BETWEEN_T;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 140 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return THEM_T;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 141 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ANGLED_T;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 142 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return DEGREE_T;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 143 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return HYPOTENUSE_T;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 144 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return FIRSTLEG_T;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 145 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return RAY_T;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 146 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return SUM_T;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 147 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return BASE_T;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 148 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ALONG_T;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 149 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return QUADRILATERAL_T;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 150 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return SQUARE_T;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 151 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return AS_T;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 152 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return MAKING_T;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 153 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return EACH_T;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 154 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return OF_T;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 155 "tokenize.l"
{if(TDEBUG) printf("Keyword %s\n", yytext); return ANGLES_T;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 157 "tokenize.l"
{
                    yylval.sval = (char*)malloc((strlen(yytext)+1)*sizeof(char));
                    strncpy(yylval.sval, yytext, strlen(yytext));
                    yylval.sval[strlen(yytext)] = '\0';
                    if(TDEBUG) printf("POINTTRIPLET %s\n", yytext);
                    return POINTTRIPLET_T;
                  }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 165 "tokenize.l"
{
              yylval.sval = (char*)malloc((strlen(yytext)+1)*sizeof(char));
              strncpy(yylval.sval, yytext, strlen(yytext));
              yylval.sval[strlen(yytext)] = '\0';
              if(TDEBUG) printf("POINTPAIR %s\n", yytext);
              return POINTPAIR_T;
            }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 173 "tokenize.l"
{
              yylval.sval = (char*)malloc((strlen(yytext)+1)*sizeof(char));
              strncpy(yylval.sval, yytext, strlen(yytext));
              yylval.sval[strlen(yytext)] = '\0';
              if(TDEBUG) printf("POINTSINGLET %s\n", yytext);
              return POINTSINGLET_T;
            }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 181 "tokenize.l"
{
              yylval.sval = (char*)malloc((strlen(yytext)+1)*sizeof(char));
              strncpy(yylval.sval, yytext, strlen(yytext));
              yylval.sval[strlen(yytext)] = '\0';
              if(TDEBUG) printf("LINELABEL %s\n", yytext);
              return LINELABEL_T;
            }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 189 "tokenize.l"
{
              yylval.ival = atoi(yytext);
              if(TDEBUG) printf("INTEGER %d\n", yylval.ival);
              return INTEGER_T;
            }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 195 "tokenize.l"
{
                   yylval.dval = toDouble(yytext);
                   if(TDEBUG) printf("REAL %lf\n", yylval.dval);
                   return REAL_T;
                 }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 201 "tokenize.l"
ECHO;
	YY_BREAK
#line 1543 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 372 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 372 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 371);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 201 "tokenize.l"


int yywrap(){return 1;}

