# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_auto_20161216_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='construction_commands',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='student',
            name='meta_lang_commands',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='student',
            name='natural_lang_commands',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
