# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_auto_20161216_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
