# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0004_auto_20161217_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
