# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0005_student_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='parent_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.State'),
        ),
    ]
