# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0006_auto_20161217_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='construction_commands',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='student',
            name='meta_lang_commands',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='student',
            name='natural_lang_commands',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
